
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import LoaderProvider from "./Loaderprovider";

import Footer from "./components/Footer";
import Cursordot from "./components/cursordot";
// import AppointmentBanner from "./components/AppointmentBanner";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
    <Cursordot />
    
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      
      <body className="min-h-full flex flex-col">{children}
        {/* <AppointmentBanner /> */}
        <LoaderProvider>
        <Footer />
        </LoaderProvider>
      </body>
    </html>
    </>
  );
}


